title: Prograde Systems Documentation
description: Technical articles and documentation for Prograde Systems
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

plugins:
  - jekyll-remote-theme

search_enabled: true
