project:
  type: website

website:
  title: "Prograde Systems"
  site-url: https://prograde-systems.github.io/
  favicon: images/prograde_systems_logo.png
  navbar:
    logo: images/prograde_systems_logo.png
    left:
      - text: Home
        file: index.qmd
      - text: Navigation
        menu:
          - text: Overview
            file: docs/navigation/index.qmd
          - text: Altimeter KF
            file: docs/navigation/altimeter_only_kf.qmd
      - text: About
        file: docs/about.qmd
  page-footer:
    center: "© 2025 Prograde Systems"

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    toc-depth: 2
    code-copy: true
